package hospicloud.async;

/**
 * Types de travaux traités de façon asynchrone via RabbitMQ.
 */
public enum AsyncJobType {
    REPORT_FACTURE,
    REPORT_ORDONNANCE,
    REPORT_CONSULTATION,
    REPORT_DOSSIER_PATIENT,
    REPORT_LISTE_PATIENTS,
    REPORT_CAISSE_DASHBOARD,
    REPORT_CAISSE_FACTURE,
    REPORT_MEDECIN_DASHBOARD,
    REPORT_ABONNEMENTS,
    REPORT_BULLETIN_SORTIE,
    REPORT_GENERIC,
    ENREGISTREMENT_PATIENT,
    ENREGISTREMENT_ARRIVEE,
    ENREGISTREMENT_UTILISATEUR
}
